### ISSUE TITLE
bug(?) with randomly unlocked vehicles

### ISSUE THREAD

**Issue by realCallMeJ** [ND-Framework/ND_Core#54] opened 2024-01-10 06:27 UTC
**Describe the bug**
when finding a randomly unlocked vehicle, you can enter, start, and drive it around, but once you exit the vehicle and re-enter, the engine will no longer start

**To Reproduce**
1. set `randomUnlockedVehicleChance` to a number in the config
2. find an unlocked vehicle and get in it
3. drive, get out, get back in it
4. you can no longer drive

**Expected behavior**
im unsure about how this was intended to work, but my best guess would be either
1) you should be able to start the car back up
2) you shouldn't be able to start the car at all

video: https://medal.tv/games/gta-v/clips/1OlndZ-WBVJTHb/d1337mC4hrP5?invite=cr-MSx3ZW4sMzczNjk4LA

**Comment by Andyyy7666** [comment] 2024-01-16 21:24
In the video you shouldn't be able to drive the car since it's not hotwired and you don't have the keys. This bug is probably caused by how the check is done.

**Comment by Andyyy7666** [comment] 2024-01-28 00:58
fixed in last release

**Closed by Andyyy7666** 2024-01-28 00:58 UTC
Labels: bug
